### ISSUE TITLE
Implement that provinceRepository findAll Promise resolves as an array of Province entities

### ISSUE THREAD

**Issue by rolandocaldas** [phpvigo/api-benchmark-reactPHP#2]
When Access to http://localhost:8000/provinces the provinces show the keys provinciaid and provincia instead of id and name as S5: http://localhost:8001/provinces

We need to change the findAll repository promise to return an array of Province entity not an array of arrays.

**Comment by dvaqueiro** [comment]
Wow, really like a ORM, even using proxy pattern as well, I don't know what else we can ask for
